import type { Metadata } from "next";
import { Header, Footer } from "@repo/ui";
import { cn } from "@repo/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DetailLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header workspace="blog" className={cn("max-w-[43.75rem]", "px-8")} />
      <div className={cn("max-w-[43.75rem]", "mx-auto", "px-8")}>
        <section className={cn("py-2")}>{children}</section>
      </div>
      <Footer className={cn("max-w-[43.75rem]", "px-8")} />
    </>
  );
}
