import type { Metadata } from "next";
import "./global.css";
import { Footer, Header } from "@repo/ui";
import { cn } from "@repo/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Header workspace="portfolio" className={cn("max-w-[52rem]", "px-8")} />
        <section className={cn("max-w-[52rem]", "mx-auto", "px-8")}>
          {children}
        </section>
        <Footer className={cn("max-w-[52rem]", "px-8")} />
      </body>
    </html>
  );
}
