import type { Metadata } from "next";
import "./global.css";
import { cn } from "@repo/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("relative")} suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
