name: App Blog prod

on:
  push:
    branches:
      - main
    paths:
      - "apps/blog/**"
      - "packages/**"
      - ".github/workflows/app-blog-prod.yml"

jobs:
  linting:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run linting
        run: turbo lint:ci --filter=blog

  unit-testing:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Run unit tests
        run: turbo test --filter=blog

